name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Setup Python ---
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- Cache pip packages ---
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # --- Install Python dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer==1.5.0 kivy==2.2.1
          pip install -r requirements.txt || true

      # --- Install system packages for Buildozer/Android ---
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev zip unzip openjdk-11-jdk zlib1g-dev \
            build-essential autoconf automake libtool pkg-config git wget curl \
            default-jdk unzip

      # --- Install Android SDK command-line tools ---
      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # --- Set Buildozer SDK and NDK paths ---
      - name: Set Buildozer SDK/NDK paths
        run: |
          sed -i '/^android.sdk_path/d' buildozer.spec || true
          sed -i '/^android.ndk_path/d' buildozer.spec || true
          echo "[global]" >> buildozer.spec
          echo "android.sdk_path = $HOME/android-sdk" >> buildozer.spec
          echo "android.ndk_path = $HOME/android-sdk/ndk-bundle" >> buildozer.spec

          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

      # --- Build APK ---
      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          buildozer android debug
          ls bin/

      # --- Upload APK as artifact ---
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LANCastReceiver-APK
          path: bin/*.apk
