name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Setup Python ---
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- Cache pip packages ---
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # --- Install dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
          pip install buildozer==1.5.0 kivy==2.2.1
          pip install -r requirements.txt || true

      # --- Install system packages for Buildozer/Android ---
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev zip unzip openjdk-11-jdk zlib1g-dev \
            build-essential autoconf automake libtool pkg-config git wget curl \
            default-jdk

      # --- Build APK ---
      - name: Build APK
        run: |
          buildozer android debug
          ls bin/

      # --- Upload APK as artifact ---
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LANCastReceiver-APK
          path: bin/*.apk
